all:
	g++ sender1.cpp -o sender1
	g++ sender2.cpp -o sender2
	g++ sender3.cpp -o sender3
	g++ receiver1.cpp -o receiver1
	g++ receiver2.cpp -o receiver2
	g++ receiver3.cpp -o receiver3
clean:
	rm -f sender1
	rm -f sender2
	rm -f sender3
	rm -f receiver1
	rm -f receiver2
	rm -f receiver3
